

export type SystemEventType =

  | "USUARIO_REGISTRADO"
  | "USUARIO_ELIMINADO"
  | "USUARIO_ACTUALIZADO"

  | "APUESTA_CREADA"
  | "APUESTA_UNIRSE"
  | "PRONOSTICO_REGISTRADO"
  | "PRONOSTICO_EDITADO"
  | "PRONOSTICO_ELIMINADO"
 
  | "ORDEN_CREADA"
  | "ORDEN_CONFIRMADA"
  | "ORDEN_CANCELADA"
 
  | "ENTRADA_COMPRADA"
  | "ENTRADA_TRANSFERIDA"
  | "ENTRADA_REEMBOLSADA"
  | "ENTRADA_LOTE_ACTIVADO"

  | "PRODUCTO_CREADO"
  | "PRODUCTO_ACTUALIZADO"
  | "PRODUCTO_DESACTIVADO"
 
  | "CATEGORIA_CREADA"
  | "CATEGORIA_ACTUALIZADA"
  | "CATEGORIA_DESACTIVADA"
  | "CATEGORIA_REACTIVADA"

  | "METODO_PAGO_AGREGADO"
  | "METODO_PAGO_ELIMINADO"

  | "PARTIDO_RESULTADO_ACTUALIZADO"
  | "PARTIDOS_SINCRONIZADOS";

export type SystemEvent = {
  id: string;
  tipo: SystemEventType;
  descripcion: string;
  fecha: string;
  idCorrelacion?: string;
  entidadCorrelacion?: string;
  usuarioId?: number;
};