export type SystemEventType =
  | "USUARIO_REGISTRADO"
  | "USUARIO_ELIMINADO"
  | "USUARIO_ACTUALIZADO"
  | "APUESTA_CREADA"
  | "APUESTA_UNIRSE"
  | "APUESTA_FINALIZADA"
  | "PRONOSTICO_REGISTRADO"
  | "PRONOSTICO_EDITADO"
  | "PRONOSTICO_ELIMINADO"
  | "ORDEN_PAGADA"
  | "ORDEN_CANCELADA"
  | "ENTRADA_RESERVADA"
  | "ENTRADA_PAGADA"
  | "ENTRADA_CANCELADA"
  | "ENTRADA_PAGO_FALLIDO"
  | "ENTRADA_REEMBOLSADA"
  | "ENTRADA_REEMBOLSO_FALLIDO"
  | "ENTRADA_EXPIRADA"
  | "ENTRADA_TRANSFERIDA"
  | "PRODUCTO_CREADO"
  | "PRODUCTO_ACTUALIZADO"
  | "PRODUCTO_DESACTIVADO"
  | "CATEGORIA_CREADA"
  | "CATEGORIA_ACTUALIZADA"
  | "CATEGORIA_DESACTIVADA"
  | "CATEGORIA_REACTIVADA"
  | "METODO_PAGO_AGREGADO"
  | "METODO_PAGO_ELIMINADO"
  | "PARTIDO_RESULTADO_ACTUALIZADO"
  | "PARTIDOS_SINCRONIZADOS";

export type SystemEvent = {
  id: string;
  tipo: SystemEventType;
  descripcion: string;
  fecha: string;
  idCorrelacion?: string;
  entidadCorrelacion?: string;
  usuarioId?: number;
};