sonar.projectKey=jsbecerrap_prueba_sonarCloud_frontend
sonar.organization=jsbecerrap
sonar.projectName=mundial-2026-frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.ts,**/*.spec.ts,**/mockDb.ts,**/poolsMockDb.ts
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/mockDb.ts,**/poolsMockDb.ts,**/config.ts,**/loginApi.ts,**/mapsApi.ts,**/http.ts,**/eventsApi.ts,**/supportApi.ts,**/groupApi.ts,**/albumApi.ts,**/marketApi.ts,**/tradesApi.ts,**/firebaseConfig.ts,**/main.tsx,**/*.test.ts
sonar.tests=src/__tests__
sonar.test.inclusions=**/*.test.ts